### ISSUE TITLE
Review background jobs for potential TIME_INSENSITIVE switch

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/office-team#14]
With https://github.com/nextcloud/server/pull/30945 it will be possible to move background jobs to times where the server is less busy. We have some tasks that currently run at a fixed interval, where it might make sense to move them for the chance of yielding better performance.

## To do

- Find out which of our background jobs are not time critical
- Move them

## Affected apps

- [x] text https://github.com/nextcloud-gmbh/server/issues/106#issuecomment-1044300427
- [x] richdocuments https://github.com/nextcloud-gmbh/server/issues/106#issuecomment-1044300427
- [x] collectives https://gitlab.com/collectivecloud/collectives/-/merge_requests/480
  - [x] https://gitlab.com/collectivecloud/collectives/-/blob/main/lib/BackgroundJob/ExpirePageVersions.php
  - [x] https://gitlab.com/collectivecloud/collectives/-/blob/main/lib/BackgroundJob/PurgeObsoleteCollectives.php
  - [x] https://gitlab.com/collectivecloud/collectives/-/blob/main/lib/BackgroundJob/PurgeObsoletePages.php
- [x] office online (unchanged - same as richdocuments)
- [x] deck
  - [x] https://github.com/nextcloud/deck/blob/master/lib/Cron/CardDescriptionActivity.php - unchanged
  - [x] https://github.com/nextcloud/deck/blob/master/lib/Cron/DeleteCron.php https://github.com/nextcloud/deck/pull/3599
  - [x] https://github.com/nextcloud/deck/blob/master/lib/Cron/ScheduledNotifications.php - unchained

**Comment by juliusknorr** [comment]
@mejo- Regarding the collectives background jobs, they all sound non-time critical, so we could potentially migrate those to become time insensitive with https://github.com/nextcloud/server/pull/30945 Can you check that?

**Comment by mejo-** [comment]
Thanks for raising this @juliushaertl. Indeed, all collectives background jobs are time-insensitive. I implemented this now in https://gitlab.com/collectivecloud/collectives/-/merge_requests/480. If you could give it a quick review, I'll merge straight away :blush:

**Comment by juliusknorr** [comment]
Thanks for taking care @mejo-
