### ISSUE TITLE
Collectives: Catch up on table support

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/office-team#18]
- [x] https://gitlab.com/collectivecloud/collectives/-/merge_requests/508
- [ ] https://github.com/nextcloud/text/pull/2278

As per discussion today, missing bits are:
- [x] Handle embedded images properly in Collectives as there is no session with read only view https://gitlab.com/collectivecloud/collectives/-/merge_requests/511

**Comment by max-nextcloud** [comment]
As discussed today in the one on one we'll probably fix the image handling in collectives itself by falling back to preview and public preview endpoint when no session is established. This way we avoid making last minute changes to text and its backend API.

**Comment by juliusknorr** [comment]
@max-nextcloud Should be all done now as far as I see, right? Apart from the package which is on the team board anyways separately.
