### ISSUE TITLE
Collectives: Page organization

### ISSUE THREAD

**Issue by juliusknorr** [nextcloud/office-team#23]
- [x] custom page order
- [x] moving pages
- [x] Emojis for pages
- [x] Improved page list

## Potential follow ups
- [ ] Favorites

**Comment by juliusknorr** [comment]
Ref https://gitlab.com/collectivecloud/collectives/-/merge_requests/584

Mostly done apart from some UI issues that may be harder to fix due to limited maintenance of the upstream drag and drop library. @vinicius73 is currently trying to reach out to them:

More todos that we postponed to later:

- [ ] Figure out how collapsion/expansion should behave when we move (delay move+exansion after hovering target) -> no automatic expansion for now
- [ ] Better UX when dragging horrizontally to switch between target level (especially relevant when drag element is last in sublist). -> let's keep it for now and reevaluate later

**Comment by vinicius73** [comment]
Related: https://github.com/SortableJS/Vue.Draggable/pull/1150

**Comment by juliusknorr** [comment]
Closing. Follow up bug fixes will be tracked in https://gitlab.com/collectivecloud/collectives/-/issues/423
